/* The following code was generated by JFlex 1.4.3 on 1/10/14 10:47 PM */

package com.haskforce;
import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import static com.haskforce.psi.HaskellTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 1/10/14 10:47 PM from the specification file
 * <tt>/Users/crobbins/IdeaProjects/HaskForce/src/com/haskforce/_HaskellLexer.flex</tt>
 */
public class _HaskellLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\47\1\4"+
    "\1\46\1\50\1\51\1\13\1\12\1\35\1\36\1\52\1\32\1\37"+
    "\1\33\1\27\1\53\1\20\7\24\2\15\1\62\1\40\1\54\1\55"+
    "\1\56\1\57\1\60\1\21\1\21\2\21\1\31\1\21\10\16\1\23"+
    "\10\16\1\25\2\16\1\41\1\5\1\42\1\34\1\14\1\43\1\6"+
    "\1\7\1\63\1\26\1\30\1\7\5\14\1\64\1\14\1\10\1\22"+
    "\2\14\1\10\1\65\1\10\1\14\1\10\1\14\1\17\2\14\1\44"+
    "\1\11\1\45\1\61\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\11\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\5\1\0"+
    "\1\45\1\0\1\46\1\47\6\0\1\50\1\51\1\52"+
    "\1\53\1\54\1\0\1\55\1\56\1\57\1\5\1\45"+
    "\2\60\2\61\1\0\2\11\1\62\1\63\1\64\1\65"+
    "\2\5\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[75];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\330\0\u010e\0\66\0\u0144"+
    "\0\66\0\u017a\0\u01b0\0\u01e6\0\u021c\0\66\0\u0252\0\66"+
    "\0\66\0\66\0\66\0\66\0\66\0\66\0\66\0\u0288"+
    "\0\66\0\u02be\0\66\0\66\0\66\0\66\0\66\0\u02f4"+
    "\0\u032a\0\66\0\66\0\66\0\66\0\u0360\0\u0396\0\242"+
    "\0\66\0\u03cc\0\66\0\66\0\u0402\0\u0438\0\u046e\0\u04a4"+
    "\0\u04da\0\u0510\0\66\0\u0546\0\66\0\66\0\u057c\0\u05b2"+
    "\0\66\0\66\0\66\0\u05e8\0\242\0\66\0\u0402\0\u061e"+
    "\0\u0654\0\u0654\0\u04da\0\u0510\0\u068a\0\u06c0\0\66\0\66"+
    "\0\u06f6\0\u072c\0\u010e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[75];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\3\3\1\4\1\5\3\6\1\7\1\10\1\11"+
    "\1\6\1\12\1\13\1\6\1\14\1\13\1\6\1\13"+
    "\1\12\1\13\1\6\1\15\1\6\1\13\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\2\6\67\0\3\3\62\0\4\50\1\51\1\52\60\50"+
    "\5\0\6\53\1\54\60\0\3\6\1\0\1\6\1\0"+
    "\13\6\1\0\2\6\31\0\3\6\5\55\1\56\4\55"+
    "\1\0\53\55\15\0\1\12\2\0\1\12\3\0\1\12"+
    "\2\0\1\57\2\60\42\0\3\13\1\0\1\13\1\0"+
    "\13\13\1\0\2\13\31\0\3\13\15\0\1\12\1\0"+
    "\1\61\1\12\1\0\2\62\1\12\1\61\1\0\1\57"+
    "\2\60\63\0\1\63\71\0\1\64\11\0\1\65\10\0"+
    "\1\66\42\0\1\67\65\0\1\70\65\0\1\71\110\0"+
    "\1\72\71\0\1\73\11\0\3\6\1\0\1\6\1\0"+
    "\13\6\1\0\2\6\31\0\1\6\1\74\1\6\4\50"+
    "\1\75\1\52\60\50\12\0\1\76\53\0\2\55\1\0"+
    "\7\55\1\77\53\55\15\0\1\100\2\0\1\100\3\0"+
    "\1\100\56\0\1\101\2\0\1\101\3\0\1\101\5\0"+
    "\2\102\40\0\2\103\5\0\1\103\2\0\2\103\2\0"+
    "\1\103\1\0\1\103\1\0\2\103\31\0\1\103\22\0"+
    "\1\104\3\0\1\104\41\0\1\105\2\0\31\105\1\106"+
    "\31\105\46\0\1\107\64\0\1\110\26\0\1\111\2\6"+
    "\1\0\1\6\1\0\13\6\1\0\2\6\31\0\3\6"+
    "\15\0\1\100\2\0\1\100\3\0\1\100\3\0\2\60"+
    "\51\0\1\101\2\0\1\101\3\0\1\101\41\0\1\105"+
    "\2\0\63\105\1\106\2\0\63\106\6\0\3\6\1\0"+
    "\1\6\1\0\13\6\1\0\2\6\31\0\2\6\1\112"+
    "\6\0\3\6\1\0\1\6\1\0\13\6\1\0\2\6"+
    "\31\0\2\6\1\113";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1890];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\1\1\1\11\4\1\1\11"+
    "\1\1\10\11\1\1\1\11\1\1\5\11\2\1\4\11"+
    "\2\1\1\0\1\11\1\0\2\11\6\0\1\11\1\1"+
    "\2\11\1\1\1\0\3\11\2\1\1\11\3\1\1\0"+
    "\4\1\2\11\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[75];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  public _HaskellLexer() {
    this((java.io.Reader)null);
  }


  public _HaskellLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public _HaskellLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 148) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 40: 
          { return DOUBLEPERIOD;
          }
        case 55: break;
        case 26: 
          { return DOLLAR;
          }
        case 56: break;
        case 35: 
          { return TILDE;
          }
        case 57: break;
        case 18: 
          { return SEMICOLON;
          }
        case 58: break;
        case 22: 
          { return LBRACE;
          }
        case 59: break;
        case 4: 
          { return BACKSLASH;
          }
        case 60: break;
        case 23: 
          { return RBRACE;
          }
        case 61: break;
        case 47: 
          { return DOUBLECOLON;
          }
        case 62: break;
        case 5: 
          { return VARIDREGEXP;
          }
        case 63: break;
        case 21: 
          { return BACKTICK;
          }
        case 64: break;
        case 10: 
          { return CONID;
          }
        case 65: break;
        case 44: 
          { return OPENCOM;
          }
        case 66: break;
        case 42: 
          { return CLOSECOM;
          }
        case 67: break;
        case 20: 
          { return RBRACKET;
          }
        case 68: break;
        case 9: 
          { return INTEGERTOKEN;
          }
        case 69: break;
        case 17: 
          { return COMMA;
          }
        case 70: break;
        case 50: 
          { return COMMENT;
          }
        case 71: break;
        case 32: 
          { return GREATERTHAN;
          }
        case 72: break;
        case 24: 
          { return HASH;
          }
        case 73: break;
        case 3: 
          { return DOUBLEQUOTE;
          }
        case 74: break;
        case 41: 
          { return DASHES;
          }
        case 75: break;
        case 25: 
          { return EXLAMATION;
          }
        case 76: break;
        case 36: 
          { return COLON;
          }
        case 77: break;
        case 31: 
          { return EQUALS;
          }
        case 78: break;
        case 8: 
          { return AMPERSAND;
          }
        case 79: break;
        case 29: 
          { return SLASH;
          }
        case 80: break;
        case 37: 
          { return STRINGTOKEN;
          }
        case 81: break;
        case 7: 
          { return SINGLEQUOTE;
          }
        case 82: break;
        case 34: 
          { return AMPERSAT;
          }
        case 83: break;
        case 39: 
          { return NULLCHARACTER;
          }
        case 84: break;
        case 27: 
          { return PERCENT;
          }
        case 85: break;
        case 48: 
          { return CHARTOKEN;
          }
        case 86: break;
        case 43: 
          { return RIGHTARROW;
          }
        case 87: break;
        case 19: 
          { return LBRACKET;
          }
        case 88: break;
        case 38: 
          { return CHARESC;
          }
        case 89: break;
        case 13: 
          { return MINUS;
          }
        case 90: break;
        case 52: 
          { return OPENPRAGMA;
          }
        case 91: break;
        case 49: 
          { return FLOATTOKEN;
          }
        case 92: break;
        case 30: 
          { return LESSTHAN;
          }
        case 93: break;
        case 45: 
          { return LEFTARROW;
          }
        case 94: break;
        case 6: 
          { return PIPE;
          }
        case 95: break;
        case 2: 
          { return com.intellij.psi.TokenType.WHITE_SPACE;
          }
        case 96: break;
        case 53: 
          { return CLOSEPRAGMA;
          }
        case 97: break;
        case 15: 
          { return LPAREN;
          }
        case 98: break;
        case 51: 
          { return HADDOCK;
          }
        case 99: break;
        case 28: 
          { return ASTERISK;
          }
        case 100: break;
        case 16: 
          { return RPAREN;
          }
        case 101: break;
        case 12: 
          { return PLUS;
          }
        case 102: break;
        case 46: 
          { return DOUBLEARROW;
          }
        case 103: break;
        case 33: 
          { return QUESTION;
          }
        case 104: break;
        case 11: 
          { return PERIOD;
          }
        case 105: break;
        case 54: 
          { return CLASSTOKEN;
          }
        case 106: break;
        case 14: 
          { return CARET;
          }
        case 107: break;
        case 1: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 108: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
