/* The following code was generated by JFlex 1.4.3 on 8/2/14 1:29 AM */

package com.haskforce.cabal.highlighting;

import com.intellij.lexer.*;
import com.intellij.psi.tree.IElementType;
import com.intellij.psi.TokenType;
import com.haskforce.cabal.psi.CabalTypes;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 8/2/14 1:29 AM from the specification file
 * <tt>/Users/crobbins/IdeaProjects/HaskForce/src/com/haskforce/cabal/highlighting/_CabalSyntaxHighlightingLexer.flex</tt>
 */
public class _CabalSyntaxHighlightingLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int WAITING_VALUE = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\1\1\0\1\3\1\2\22\0\1\5\14\0\1\7"+
    "\2\0\12\4\1\6\6\0\1\22\1\24\1\14\1\0\1\10\3\0"+
    "\1\30\2\0\1\26\5\0\1\32\1\36\1\20\1\16\2\0\1\12"+
    "\1\34\7\0\1\23\1\25\1\15\1\4\1\11\3\4\1\31\2\4"+
    "\1\27\5\4\1\33\1\37\1\21\1\17\2\4\1\13\1\35\1\4"+
    "\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\1\1\4\7\1\4\5"+
    "\2\0\1\6\1\7\16\0\1\10\7\0\1\11\56\0"+
    "\2\12\12\0\1\12\1\6\4\0\1\11\10\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\40\0\100\0\100\0\140\0\200\0\240\0\100"+
    "\0\300\0\340\0\u0100\0\u0120\0\u0140\0\u0160\0\u0180\0\100"+
    "\0\u01a0\0\u01c0\0\u01e0\0\240\0\u0200\0\100\0\u0220\0\u0240"+
    "\0\u0260\0\u0280\0\u02a0\0\u02c0\0\u02e0\0\u01a0\0\u0300\0\u0320"+
    "\0\u0340\0\u0360\0\u0380\0\u03a0\0\u03c0\0\u03e0\0\u0400\0\u0420"+
    "\0\u0440\0\u0460\0\u0480\0\u04a0\0\u04c0\0\100\0\u04e0\0\u0500"+
    "\0\u0520\0\u0540\0\u0560\0\u0580\0\u05a0\0\u05c0\0\u05e0\0\u0600"+
    "\0\u0620\0\u0640\0\u0660\0\u0680\0\u06a0\0\u06c0\0\u06e0\0\u0700"+
    "\0\u0720\0\u0740\0\u0760\0\u0780\0\u07a0\0\u07c0\0\u07e0\0\u0800"+
    "\0\u0820\0\u0840\0\u0860\0\u0880\0\u08a0\0\u08c0\0\u08e0\0\u0900"+
    "\0\u0920\0\u0940\0\u0960\0\u0980\0\u09a0\0\u09c0\0\u09e0\0\u0a00"+
    "\0\u0a20\0\u0a40\0\u0a60\0\u0a80\0\u0aa0\0\u0ac0\0\u0ae0\0\u0b00"+
    "\0\u0b20\0\u0b40\0\u0b60\0\u0b80\0\u0ba0\0\u0bc0\0\u0be0\0\u0c00"+
    "\0\u0c20\0\u0aa0\0\u0c40\0\u0c60\0\u0c80\0\u0ca0\0\u0cc0\0\u0ce0"+
    "\0\u0d00\0\u0d20\0\u0d40\0\u0d60\0\u0d80\0\u0da0\0\u0dc0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\6\1\10\1\11"+
    "\1\12\1\13\1\3\1\7\1\3\1\7\1\3\1\7"+
    "\1\14\1\15\1\3\1\7\1\3\1\7\1\16\1\17"+
    "\1\3\1\7\1\3\1\7\1\3\1\7\1\3\1\7"+
    "\1\20\1\21\1\22\4\20\1\23\30\20\41\0\1\4"+
    "\41\0\1\6\1\0\1\6\36\0\1\24\1\25\1\26"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\4\0\1\24\1\25\1\26\1\27\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\12\0\2\30"+
    "\30\0\1\24\1\25\1\26\1\24\1\0\1\24\1\30"+
    "\1\31\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\10\0\2\32\32\0"+
    "\1\24\1\25\1\26\1\24\1\32\1\33\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\30\0\2\34\12\0\1\24"+
    "\1\25\1\26\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\34\1\35\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\3\0\1\36\1\37\1\36\1\0"+
    "\1\37\1\40\1\41\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\42\1\43\1\0\1\37\1\0\1\37\1\44"+
    "\1\45\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\36\1\0\1\36\1\37\1\36\1\0"+
    "\1\37\1\40\1\41\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\42\1\43\1\0\1\37\1\0\1\37\1\44"+
    "\1\45\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\7\0\1\46\35\0\1\25\1\26\31\0\1\27"+
    "\2\0\35\27\10\0\2\47\32\0\1\24\1\25\1\26"+
    "\1\24\1\47\1\50\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\36\0\2\51\4\0\1\24\1\25\1\26\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\51\1\52"+
    "\24\0\2\53\16\0\1\24\1\25\1\26\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\53\1\54\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\4\0"+
    "\1\37\1\55\1\56\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\12\0\2\57\30\0\1\37"+
    "\1\55\1\56\1\37\1\0\1\37\1\57\1\60\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\10\0\2\61\32\0\1\37\1\55"+
    "\1\56\1\37\1\61\1\62\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\30\0\2\63\12\0\1\37\1\55\1\56"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\63\1\64\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\46\2\0\35\46\14\0\2\65\26\0\1\24"+
    "\1\25\1\26\1\24\1\0\1\24\1\0\1\24\1\65"+
    "\1\66\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\20\0\2\67\22\0\1\24\1\25"+
    "\1\26\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\67\1\70\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\32\0\2\71\10\0\1\24\1\25\1\26"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\71\1\72\1\0\1\24\1\0"+
    "\1\24\5\0\1\55\1\56\41\0\2\73\32\0\1\37"+
    "\1\55\1\56\1\37\1\73\1\74\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\36\0\2\75\4\0\1\37\1\55"+
    "\1\56\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\75\1\76\24\0\2\77\16\0\1\37\1\55\1\56"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\77\1\100\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\16\0\2\101\24\0\1\24\1\25\1\26\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\101\1\102"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\7\0\1\103\34\0\1\24\1\25\1\26\1\104\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\22\0"+
    "\2\105\20\0\1\24\1\25\1\26\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\105\1\106\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\14\0\2\107"+
    "\26\0\1\37\1\55\1\56\1\37\1\0\1\37\1\0"+
    "\1\37\1\107\1\110\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\20\0\2\111\22\0"+
    "\1\37\1\55\1\56\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\111\1\112\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\32\0\2\113\10\0\1\37"+
    "\1\55\1\56\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\113\1\114\1\0"+
    "\1\37\1\0\1\37\20\0\2\115\22\0\1\24\1\25"+
    "\1\26\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\115\1\116\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\36\0\2\117\4\0\1\24\1\25\1\26"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\117"+
    "\1\120\32\0\2\121\10\0\1\24\1\25\1\26\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\121\1\122\1\0\1\24\1\0\1\24"+
    "\16\0\2\123\24\0\1\37\1\55\1\56\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\123\1\124\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\7\0"+
    "\1\125\34\0\1\37\1\55\1\56\1\126\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\22\0\2\127"+
    "\20\0\1\37\1\55\1\56\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\127"+
    "\1\130\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\22\0\2\131\20\0"+
    "\1\24\1\25\1\26\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\131\1\132"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\16\0\2\133\24\0\1\24"+
    "\1\25\1\26\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\133\1\134\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\34\0\2\135\6\0\1\24\1\25"+
    "\1\26\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\135\1\136"+
    "\1\0\1\24\20\0\2\137\22\0\1\37\1\55\1\56"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\137\1\140\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\36\0\2\141\4\0\1\37\1\55\1\56\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\141\1\142"+
    "\32\0\2\143\10\0\1\37\1\55\1\56\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\143\1\144\1\0\1\37\1\0\1\37\24\0"+
    "\2\145\16\0\1\24\1\25\1\26\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\145\1\146\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\30\0\2\147"+
    "\12\0\1\24\1\25\1\26\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\147\1\150\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\135\2\0\36\135"+
    "\2\0\1\135\1\136\1\151\1\152\1\136\1\135\1\136"+
    "\1\135\1\136\1\135\1\136\1\135\1\136\1\135\1\136"+
    "\1\135\1\136\1\135\1\136\1\135\1\136\1\135\1\136"+
    "\1\135\1\136\1\135\1\136\1\135\1\136\22\0\2\153"+
    "\20\0\1\37\1\55\1\56\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\153"+
    "\1\154\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\16\0\2\155\24\0"+
    "\1\37\1\55\1\56\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\155\1\156\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\34\0\2\157\6\0\1\37"+
    "\1\55\1\56\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\2\157"+
    "\1\0\1\37\26\0\2\160\14\0\1\24\1\25\1\26"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\1\0\1\24\1\0\1\24\1\0\1\24\1\160"+
    "\1\161\1\0\1\24\1\0\1\24\1\0\1\24\1\0"+
    "\1\24\20\0\2\160\22\0\1\24\1\25\1\26\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\160\1\161\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\135\2\0\2\135\1\151\1\152\31\135\24\0\2\162"+
    "\16\0\1\37\1\55\1\56\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\162\1\163\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\30\0\2\164\12\0"+
    "\1\37\1\55\1\56\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\164\1\165\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\157\2\0\35\157\10\0"+
    "\2\135\32\0\1\24\1\25\1\26\1\24\1\135\1\136"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\1\0\1\24"+
    "\1\0\1\24\1\0\1\24\1\0\1\24\26\0\2\166"+
    "\14\0\1\37\1\55\1\56\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\166\1\167\1\0\1\37\1\0"+
    "\1\37\1\0\1\37\1\0\1\37\20\0\2\166\22\0"+
    "\1\37\1\55\1\56\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\166\1\167\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\10\0\2\157\32\0\1\37"+
    "\1\55\1\56\1\37\2\157\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37\1\0\1\37\1\0\1\37\1\0\1\37"+
    "\1\0\1\37";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3552];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\3\1\1\11\7\1\1\11\3\1\2\0"+
    "\1\11\1\1\16\0\1\1\7\0\1\11\56\0\2\1"+
    "\12\0\2\1\4\0\1\1\10\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  public _CabalSyntaxHighlightingLexer() {
    this((java.io.Reader)null);
  }


  public _CabalSyntaxHighlightingLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public _CabalSyntaxHighlightingLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 102) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 10: 
          { yybegin(YYINITIAL); return CabalTypes.CONFIG;
          }
        case 11: break;
        case 8: 
          { return CabalTypes.COMMENT;
          }
        case 12: break;
        case 6: 
          { yypushback(1); yybegin(YYINITIAL); return CabalTypes.KEY;
          }
        case 13: break;
        case 3: 
          { yybegin(YYINITIAL); return TokenType.WHITE_SPACE;
          }
        case 14: break;
        case 9: 
          { yypushback(yylength()); yybegin(YYINITIAL); return CabalTypes.CRLF;
          }
        case 15: break;
        case 7: 
          { yybegin(YYINITIAL); return CabalTypes.COMMENT;
          }
        case 16: break;
        case 2: 
          { yybegin(YYINITIAL); return CabalTypes.CRLF;
          }
        case 17: break;
        case 4: 
          { yybegin(WAITING_VALUE); return CabalTypes.COLON;
          }
        case 18: break;
        case 1: 
          { return TokenType.BAD_CHARACTER;
          }
        case 19: break;
        case 5: 
          { return CabalTypes.VALUE_CHAR;
          }
        case 20: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
