#!/bin/bash

set -e

cd "$(dirname "$0")/../.."

parser_yaml=./tools/parser/parser2020.yaml
out_scala=./src/com/haskforce/haskell/lang/parser/gen/HaskellParserInfra2020.scala

mkdir -p "$(dirname "$out_scala")"

# Creating a temp file which helps refresh the file in-place in the IDE
# without first truncating.
tmp_scala=$(mktemp -t "$(basename "$out_scala")")
./tools/parser/gen-types.hs "$parser_yaml" > "$tmp_scala"
mv "$tmp_scala" "$out_scala"

echo "Generated scala file: $out_scala"
