#!/bin/bash

set -e

cd "$(dirname "$0")/../.."

parser_yaml=./tools/parser/parser2020.yaml
out_scala=./src/com/haskforce/haskell/lang/parser/gen/HaskellParserInfra2020.scala

mkdir -p "$(dirname "$out_scala")"

# Writing to a temp file first to so we ensure generation is successful before
# overwriting the existing file.
tmp_scala=$(mktemp -t "$(basename "$out_scala")")
./tools/parser/gen-types.hs "$parser_yaml" > "$tmp_scala"
mv "$tmp_scala" "$out_scala"

echo "Generated scala file: $out_scala"
