#!/bin/bash

basedir=$(dirname $0)/..
cabal_flex=$basedir/src/com/haskforce/cabal/lang/lexer/_CabalParsingLexer.flex
delim=' '

[ -z "$1" ] || delim=$1

delim_length=$(($(wc -c <<< "$delim") - 1))

egrep -o 'CabalTypes.([A-Z_]+)' "$cabal_flex" \
  | sort | uniq \
  | grep -v WHITE_SPACE \
  | cut -d '.' -f 2 \
  | xargs -n1 printf "%s$delim" \
  | head -c "-$delim_length" \
  | fold -w 80 -s
printf '\n'
