#!/bin/bash

set -e

DIC="$(dirname "$0")/../resources/dictionary/haskell.dic"

get_unique() {
  sort "$DIC" | uniq
}

invalid_words() {
  egrep -i '[^a-z]' "$DIC" || true
}

case "$1" in
  "--overwrite")
    RESULT=$(valid)
    echo "$RESULT" > "$DIC"
    ;;
  "--show")
    get_unique
    ;;
  "")
    (get_unique | cmp - "$DIC" 2>&1 > /dev/null) || {
      >&2 echo "haskell.dic contains unsorted or duplicate words."
      exit 1
    }
    INVALID="$(invalid_words)"
    if [ -n "$INVALID" ]; then
      >&2 echo "Invalid words found:"
      while read -r word; do
        >&2 echo " * '$word'"
      done <<< "$INVALID"
      exit 1
    fi
    echo "$DIC is valid"
    ;;
  *)
    >&2 echo "Usage: $0 [--overwrite]"
    exit 1
    ;;
esac
